# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('number', models.CharField(default=uuid.uuid1, max_length=255, unique=True, verbose_name='\u7f16\u53f7')),
                ('image_base64', models.BinaryField(null=True, verbose_name='Base64\u7f16\u7801\u56fe\u7247')),
                ('image', models.ImageField(blank=True, null=True, upload_to='info_management/image', verbose_name='\u7167\u7247')),
                ('feature', models.CharField(max_length=255, verbose_name='\u7279\u5f81\u503c')),
            ],
            options={
                'verbose_name': '\u5458\u5de5\u4fe1\u606f',
                'verbose_name_plural': '\u5458\u5de5\u4fe1\u606f',
            },
        ),
    ]
