# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleinfo',
            options={'verbose_name': '\u4eba\u5458\u4fe1\u606f', 'verbose_name_plural': '\u4eba\u5458\u4fe1\u606f'},
        ),
    ]
