# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info_management', '0010_auto_20190311_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelinfo',
            name='name',
            field=models.CharField(default=123456, max_length=50, verbose_name='\u59d3\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelinfo',
            name='number',
            field=models.UUIDField(default=uuid.uuid1, unique=True, verbose_name='\u7f16\u53f7'),
        ),
    ]
