# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 03:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_management', '0011_auto_20190311_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelinfo',
            options={'verbose_name': '\u5458\u5de5\u4fe1\u606f', 'verbose_name_plural': '\u5458\u5de5\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='matchingrecord',
            name='people',
            field=models.ForeignKey(default=123456, on_delete=django.db.models.deletion.CASCADE, to='info_management.PersonnelInfo', verbose_name='\u5339\u914d\u4eba\u5458'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchingrecord',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 11, 11, 55, 45, 696000), verbose_name='\u5339\u914d\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='matchingrecord',
            name='type',
            field=models.CharField(choices=[('IN', '\u5165'), ('OUT', '\u51fa'), ('UNKNOWN', '\u672a\u8bbe\u7f6e')], default=123456, max_length=7, verbose_name='\u5339\u914d\u8bb0\u5f55'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='info_management/image', verbose_name='\u7167\u7247'),
        ),
        migrations.AddField(
            model_name='personnelinfo',
            name='image_base64',
            field=models.TextField(null=True, verbose_name='Base64\u7f16\u7801\u56fe\u7247'),
        ),
    ]
