# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 06:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_management', '0012_auto_20190311_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonnelInfo',
            new_name='PeopleInfo',
        ),
        migrations.AlterField(
            model_name='matchingrecord',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 12, 14, 44, 32, 534000), verbose_name='\u5339\u914d\u65f6\u95f4'),
        ),
    ]
