# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_management', '0013_auto_20190312_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingrecord',
            name='people',
        ),
        migrations.AddField(
            model_name='matchingrecord',
            name='peoples',
            field=models.ForeignKey(default=123456, on_delete=django.db.models.deletion.CASCADE, to='info_management.PeopleInfo', verbose_name='\u5339\u914d\u4eba\u5458'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchingrecord',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 12, 14, 47, 41, 775000), verbose_name='\u5339\u914d\u65f6\u95f4'),
        ),
    ]
