# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_management', '0014_auto_20190312_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingrecord',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 12, 14, 48, 57, 140000), verbose_name='\u5339\u914d\u65f6\u95f4'),
        ),
    ]
