# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_management', '0015_auto_20190312_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='peopleinfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='peopleinfo',
            name='image_base64',
        ),
        migrations.RemoveField(
            model_name='peopleinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='peopleinfo',
            name='number',
        ),
        migrations.AlterField(
            model_name='matchingrecord',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 12, 14, 49, 54, 611000), verbose_name='\u5339\u914d\u65f6\u95f4'),
        ),
    ]
