# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info_management', '0016_auto_20190312_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleinfo',
            options={'verbose_name': '\u5458\u5de5\u4fe1\u606f', 'verbose_name_plural': '\u5458\u5de5\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='peopleinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='info_management/image', verbose_name='\u7167\u7247'),
        ),
        migrations.AddField(
            model_name='peopleinfo',
            name='image_base64',
            field=models.TextField(null=True, verbose_name='Base64\u7f16\u7801\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='peopleinfo',
            name='name',
            field=models.CharField(default=123456, max_length=50, verbose_name='\u59d3\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peopleinfo',
            name='number',
            field=models.UUIDField(default=uuid.uuid1, unique=True, verbose_name='\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='matchingrecord',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 12, 14, 50, 33, 35000), verbose_name='\u5339\u914d\u65f6\u95f4'),
        ),
    ]
