# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_management', '0018_auto_20190312_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingrecord',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 13, 11, 53, 51, 32000), verbose_name='\u5339\u914d\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='image_base64',
            field=models.FileField(null=True, upload_to=b'', verbose_name='Base64\u7f16\u7801\u56fe\u7247'),
        ),
    ]
