# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 05:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_management', '0019_auto_20190313_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingrecord',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 13, 13, 54, 15, 388000), verbose_name='\u5339\u914d\u65f6\u95f4'),
        ),
    ]
