# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 01:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info_management', '0021_auto_20190313_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingrecord',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 14, 9, 53, 8, 741000), verbose_name='\u5339\u914d\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='number',
            field=models.CharField(default=uuid.uuid1, max_length=255, unique=True, verbose_name='\u7f16\u53f7'),
        ),
    ]
