# Generated by Django 2.1b1 on 2018-07-09 12:05

import picklefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', picklefield.fields.PickledObjectField(editable=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
