# Generated by Django 2.1b1 on 2018-07-10 05:39

import picklefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_auto_20180710_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='content',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
