# Generated by Django 2.0.7 on 2018-09-26 08:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_auto_20180710_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备名')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='设备信息')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='设备组名')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='devices', to='sync.DeviceGroup', verbose_name='设备分组'),
        ),
    ]
