# Generated by Django 2.0.7 on 2018-09-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_auto_20180927_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name',), 'verbose_name': '设备', 'verbose_name_plural': '设备列表'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='group',
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('IN', '入'), ('OUT', '出'), ('UNKNOWN', '未设置')], default='UNKNOWN', max_length=255),
        ),
        migrations.DeleteModel(
            name='DeviceGroup',
        ),
    ]
