# Generated by Django 2.0.7 on 2018-12-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0008_auto_20181217_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='设备名'),
        ),
    ]
