# Generated by Django 2.0.7 on 2018-12-26 01:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0009_auto_20181225_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, unique=True, verbose_name='UUID'),
        ),
    ]
