# Generated by Django 2.0.7 on 2018-12-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0010_auto_20181226_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('IN', '入'), ('OUT', '出'), ('UNKNOWN', '未设置')], default='UNKNOWN', max_length=255, verbose_name='设备类型'),
        ),
    ]
