# Generated by Django 2.1.2 on 2018-12-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0011_auto_20181226_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='device',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='设备位置'),
        ),
    ]
