# Generated by Django 2.1.2 on 2019-01-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0012_auto_20181229_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP地址'),
        ),
    ]
