# Generated by Django 2.0.5 on 2018-07-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('name', 'position'), 'verbose_name': '人员', 'verbose_name_plural': '人员列表'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('created', 'target'), 'verbose_name': '匹配记录', 'verbose_name_plural': '匹配记录列表'},
        ),
        migrations.RemoveField(
            model_name='record',
            name='image',
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.TextField(verbose_name='Base64编码图片'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(max_length=255, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='rest.Person', verbose_name='匹配目标'),
        ),
    ]
