# Generated by Django 2.0.5 on 2018-07-05 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20180705_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created',
            field=models.DateTimeField(verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='rest.Person', verbose_name='匹配目标'),
            preserve_default=False,
        ),
    ]
