# Generated by Django 2.0.3 on 2018-07-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20180705_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='raw_image',
            field=models.ImageField(default=1, upload_to='img', verbose_name='照片'),
            preserve_default=False,
        ),
    ]
