# Generated by Django 2.0.3 on 2018-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_person_raw_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='raw_image',
            field=models.ImageField(null=True, upload_to='img', verbose_name='照片'),
        ),
    ]
