# Generated by Django 2.0.3 on 2018-07-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20180706_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.TextField(null=True, verbose_name='Base64编码图片'),
        ),
    ]
