# Generated by Django 2.0.3 on 2018-07-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20180706_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='raw_image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='照片'),
        ),
    ]
