# Generated by Django 2.1b1 on 2018-07-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20180707_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('-created', 'target'), 'verbose_name': '匹配记录', 'verbose_name_plural': '匹配记录列表'},
        ),
    ]
