# Generated by Django 2.0.7 on 2018-07-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_person_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
    ]
