# Generated by Django 2.0.7 on 2018-09-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20180723_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('-created', 'target', 'record_type'), 'verbose_name': '匹配记录', 'verbose_name_plural': '匹配记录列表'},
        ),
        migrations.AddField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('IN', '入'), ('OUT', '出'), ('UNKNOWN', '未设置')], default='UNKNOWN', max_length=255),
        ),
    ]
