# Generated by Django 2.0.7 on 2018-12-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_auto_20180928_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='employee_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='工号'),
        ),
    ]
