# Generated by Django 2.0.7 on 2018-12-29 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_person_employee_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('is_active', 'name', 'position'), 'verbose_name': '人员', 'verbose_name_plural': '人员列表'},
        ),
    ]
