# Generated by Django 2.0.7 on 2018-12-29 07:15

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_auto_20181229_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='employment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
