# Generated by Django 2.0.7 on 2018-12-29 07:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_person_employment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='employment_date',
            field=models.DateField(default=datetime.date.today, verbose_name='入职时间'),
        ),
    ]
