# Generated by Django 2.0.7 on 2018-12-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_auto_20181229_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, help_text='未激活即为离职状态', verbose_name='是否激活'),
        ),
    ]
