# Generated by Django 2.1.2 on 2018-12-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_auto_20181229_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-is_active', 'name', 'position', 'employee_number', 'employment_date'), 'verbose_name': '人员', 'verbose_name_plural': '人员列表'},
        ),
    ]
