# Generated by Django 2.1.2 on 2019-01-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_auto_20181229_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='employee_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='工号'),
        ),
    ]
