# Generated by Django 2.1.2 on 2019-01-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_auto_20190103_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.CharField(choices=[('HARDWARE', '硬件部'), ('SOFTWARE', '软件部'), ('MARKET', '市场部'), ('UNKNOWN', '未知')], default='UNKNOWN', max_length=255, verbose_name='设备类型'),
        ),
    ]
