# Generated by Django 2.1.2 on 2019-01-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0021_person_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(choices=[('HARDWARE', '硬件部'), ('SOFTWARE', '软件部'), ('MARKET', '市场部'), ('UNKNOWN', '未知')], default='UNKNOWN', max_length=255, verbose_name='所属部门'),
        ),
    ]
