# Generated by Django 2.1.2 on 2019-01-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0022_auto_20190111_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(choices=[('硬件部', '硬件部'), ('软件部', '软件部'), ('市场部', '市场部'), ('未知', '未知')], default='未知', max_length=255, verbose_name='所属部门'),
        ),
    ]
