# Generated by Django 2.1.2 on 2019-01-16 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_auto_20190111_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='employee_number',
            field=models.CharField(default=uuid.uuid1, max_length=255, verbose_name='工号'),
        ),
    ]
