# Generated by Django 2.1.7 on 2019-02-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0025_auto_20190223_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.ForeignKey(on_delete=models.SET('未知'), related_name='department_name', to='rest.Department', verbose_name='部门'),
        ),
    ]
