# Generated by Django 2.1.7 on 2019-02-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0027_auto_20190223_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='离职时间'),
        ),
    ]
