# Generated by Django 2.1.7 on 2019-02-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0029_auto_20190223_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('未知'), related_name='department_name', to='rest.Department', to_field='name', verbose_name='部门'),
        ),
    ]
