# Generated by Django 2.1.7 on 2019-02-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0030_auto_20190225_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_name', to='rest.Department', to_field='name', verbose_name='部门'),
        ),
    ]
