# Generated by Django 2.1.7 on 2019-03-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0036_auto_20190301_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
    ]
